name: My Project's Testing CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deno_ci:
    uses: cross-org/workflows/deno-ci.yml@main
    with:
      entrypoint: mod.ts
  bun_ci:
    uses: cross-org/workflows/bun-ci.yml@main
    with:
      jsr_dependencies: @cross/test @std/assert
  node_ci:
    uses: cross-org/workflows/node-ci.yml@main
    with:
      jsr_dependencies: @cross/test @std/assert